-- Create a supplemental Home sections collection instead of exceeding D1's
-- 100-column limit on the legacy site_pages table.
CREATE TABLE IF NOT EXISTS ec_site_home_sections (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  home_birth_chart_eyebrow TEXT,
  home_birth_chart_title_accent TEXT,
  home_birth_chart_title_rest TEXT,
  home_birth_chart_description TEXT,
  home_birth_chart_form_title TEXT,
  home_birth_chart_date_label TEXT,
  home_birth_chart_time_label TEXT,
  home_birth_chart_unknown_time_label TEXT,
  home_birth_chart_location_label TEXT,
  home_birth_chart_location_placeholder TEXT,
  home_birth_chart_location_start TEXT,
  home_birth_chart_location_searching TEXT,
  home_birth_chart_location_empty TEXT,
  home_birth_chart_location_unavailable TEXT,
  home_birth_chart_location_selected TEXT,
  home_birth_chart_extended_settings_label TEXT,
  home_birth_chart_house_system_label TEXT,
  home_birth_chart_house_placidus TEXT,
  home_birth_chart_house_whole_sign TEXT,
  home_birth_chart_house_koch TEXT,
  home_birth_chart_house_equal TEXT,
  home_birth_chart_show_aspects_label TEXT,
  home_birth_chart_cta TEXT,
  home_birth_chart_wheel_title TEXT,
  home_birth_chart_wheel_description TEXT,
  home_birth_chart_feature_1_title TEXT,
  home_birth_chart_feature_1_body TEXT,
  home_birth_chart_feature_2_title TEXT,
  home_birth_chart_feature_2_body TEXT,
  home_birth_chart_feature_3_title TEXT,
  home_birth_chart_feature_3_body TEXT,
  UNIQUE(slug, locale)
);
