CREATE TABLE IF NOT EXISTS ec_site_synastry (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  topbar_label TEXT,
  eyebrow TEXT,
  title_accent TEXT,
  title_rest TEXT,
  description TEXT,
  relationship_label TEXT,
  relationship_romantic TEXT,
  relationship_friendship TEXT,
  relationship_family TEXT,
  relationship_work TEXT,
  person_one_title TEXT,
  person_two_title TEXT,
  name_label TEXT,
  person_one_placeholder TEXT,
  person_two_placeholder TEXT,
  birth_date_label TEXT,
  month_label TEXT,
  day_label TEXT,
  year_label TEXT,
  birth_time_label TEXT,
  hour_label TEXT,
  minute_label TEXT,
  period_label TEXT,
  unknown_time_label TEXT,
  unknown_time_description TEXT,
  birth_place_label TEXT,
  location_placeholder TEXT,
  location_start TEXT,
  location_searching TEXT,
  location_empty TEXT,
  location_unavailable TEXT,
  location_selected TEXT,
  submit_label TEXT,
  footer_text TEXT,
  seo_title TEXT,
  seo_description TEXT,
  seo_canonical_path TEXT,
  seo_robots TEXT,
  og_title TEXT,
  og_description TEXT,
  og_image TEXT,
  og_image_alt TEXT,
  twitter_card TEXT,
  twitter_title TEXT,
  twitter_description TEXT,
  twitter_image TEXT,
  UNIQUE(slug, locale)
);
