CREATE TABLE IF NOT EXISTS ec_site_home_horoscope (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  home_horoscope_eyebrow TEXT,
  home_horoscope_title_accent TEXT,
  home_horoscope_title_rest TEXT,
  home_horoscope_prompt TEXT,
  home_horoscope_sign_1_name TEXT,
  home_horoscope_sign_1_dates TEXT,
  home_horoscope_sign_1_element TEXT,
  home_horoscope_sign_1_reading TEXT,
  home_horoscope_sign_1_cta TEXT,
  home_horoscope_sign_2_name TEXT,
  home_horoscope_sign_2_dates TEXT,
  home_horoscope_sign_2_element TEXT,
  home_horoscope_sign_2_reading TEXT,
  home_horoscope_sign_2_cta TEXT,
  home_horoscope_sign_3_name TEXT,
  home_horoscope_sign_3_dates TEXT,
  home_horoscope_sign_3_element TEXT,
  home_horoscope_sign_3_reading TEXT,
  home_horoscope_sign_3_cta TEXT,
  home_horoscope_sign_4_name TEXT,
  home_horoscope_sign_4_dates TEXT,
  home_horoscope_sign_4_element TEXT,
  home_horoscope_sign_4_reading TEXT,
  home_horoscope_sign_4_cta TEXT,
  home_horoscope_sign_5_name TEXT,
  home_horoscope_sign_5_dates TEXT,
  home_horoscope_sign_5_element TEXT,
  home_horoscope_sign_5_reading TEXT,
  home_horoscope_sign_5_cta TEXT,
  home_horoscope_sign_6_name TEXT,
  home_horoscope_sign_6_dates TEXT,
  home_horoscope_sign_6_element TEXT,
  home_horoscope_sign_6_reading TEXT,
  home_horoscope_sign_6_cta TEXT,
  home_horoscope_sign_7_name TEXT,
  home_horoscope_sign_7_dates TEXT,
  home_horoscope_sign_7_element TEXT,
  home_horoscope_sign_7_reading TEXT,
  home_horoscope_sign_7_cta TEXT,
  home_horoscope_sign_8_name TEXT,
  home_horoscope_sign_8_dates TEXT,
  home_horoscope_sign_8_element TEXT,
  home_horoscope_sign_8_reading TEXT,
  home_horoscope_sign_8_cta TEXT,
  home_horoscope_sign_9_name TEXT,
  home_horoscope_sign_9_dates TEXT,
  home_horoscope_sign_9_element TEXT,
  home_horoscope_sign_9_reading TEXT,
  home_horoscope_sign_9_cta TEXT,
  home_horoscope_sign_10_name TEXT,
  home_horoscope_sign_10_dates TEXT,
  home_horoscope_sign_10_element TEXT,
  home_horoscope_sign_10_reading TEXT,
  home_horoscope_sign_10_cta TEXT,
  home_horoscope_sign_11_name TEXT,
  home_horoscope_sign_11_dates TEXT,
  home_horoscope_sign_11_element TEXT,
  home_horoscope_sign_11_reading TEXT,
  home_horoscope_sign_11_cta TEXT,
  home_horoscope_sign_12_name TEXT,
  home_horoscope_sign_12_dates TEXT,
  home_horoscope_sign_12_element TEXT,
  home_horoscope_sign_12_reading TEXT,
  home_horoscope_sign_12_cta TEXT,
  UNIQUE(slug, locale)
);
