CREATE TABLE IF NOT EXISTS ec_site_home_astrologers (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  home_astrologers_eyebrow TEXT,
  home_astrologers_title_accent TEXT,
  home_astrologers_title_rest TEXT,
  home_astrologers_browse_label TEXT,
  home_astrologers_profile_1_name TEXT,
  home_astrologers_profile_1_tradition TEXT,
  home_astrologers_profile_1_availability_label TEXT,
  home_astrologers_profile_1_rating TEXT,
  home_astrologers_profile_1_rate TEXT,
  home_astrologers_profile_1_rate_unit TEXT,
  home_astrologers_profile_1_action TEXT,
  home_astrologers_profile_2_name TEXT,
  home_astrologers_profile_2_tradition TEXT,
  home_astrologers_profile_2_availability_label TEXT,
  home_astrologers_profile_2_rating TEXT,
  home_astrologers_profile_2_rate TEXT,
  home_astrologers_profile_2_rate_unit TEXT,
  home_astrologers_profile_2_action TEXT,
  home_astrologers_profile_3_name TEXT,
  home_astrologers_profile_3_tradition TEXT,
  home_astrologers_profile_3_availability_label TEXT,
  home_astrologers_profile_3_rating TEXT,
  home_astrologers_profile_3_rate TEXT,
  home_astrologers_profile_3_rate_unit TEXT,
  home_astrologers_profile_3_action TEXT,
  home_astrologers_profile_4_name TEXT,
  home_astrologers_profile_4_tradition TEXT,
  home_astrologers_profile_4_availability_label TEXT,
  home_astrologers_profile_4_rating TEXT,
  home_astrologers_profile_4_rate TEXT,
  home_astrologers_profile_4_rate_unit TEXT,
  home_astrologers_profile_4_action TEXT,
  UNIQUE(slug, locale)
);
