CREATE TABLE IF NOT EXISTS ec_site_home_reports (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  home_reports_eyebrow TEXT,
  home_reports_title_accent TEXT,
  home_reports_title_rest TEXT,
  home_reports_browse_label TEXT,
  home_reports_report_1_title TEXT,
  home_reports_report_1_description TEXT,
  home_reports_report_1_pages TEXT,
  home_reports_report_1_price TEXT,
  home_reports_report_1_action TEXT,
  home_reports_report_2_title TEXT,
  home_reports_report_2_description TEXT,
  home_reports_report_2_pages TEXT,
  home_reports_report_2_price TEXT,
  home_reports_report_2_action TEXT,
  home_reports_report_3_title TEXT,
  home_reports_report_3_description TEXT,
  home_reports_report_3_pages TEXT,
  home_reports_report_3_price TEXT,
  home_reports_report_3_action TEXT,
  UNIQUE(slug, locale)
);
