CREATE TABLE IF NOT EXISTS ec_site_home_shop (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  home_shop_eyebrow TEXT,
  home_shop_title_lead TEXT,
  home_shop_title_accent TEXT,
  home_shop_title_rest TEXT,
  home_shop_browse_label TEXT,
  home_shop_item_1_title TEXT,
  home_shop_item_1_category TEXT,
  home_shop_item_1_price TEXT,
  home_shop_item_1_image_alt TEXT,
  home_shop_item_2_title TEXT,
  home_shop_item_2_category TEXT,
  home_shop_item_2_price TEXT,
  home_shop_item_2_image_alt TEXT,
  home_shop_item_3_title TEXT,
  home_shop_item_3_category TEXT,
  home_shop_item_3_price TEXT,
  home_shop_item_3_image_alt TEXT,
  home_shop_item_4_title TEXT,
  home_shop_item_4_category TEXT,
  home_shop_item_4_price TEXT,
  home_shop_item_4_image_alt TEXT,
  UNIQUE(slug, locale)
);
