CREATE TABLE IF NOT EXISTS ec_site_home_blog (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  home_blog_title_accent TEXT,
  home_blog_title_rest TEXT,
  home_blog_tagline TEXT,
  home_blog_browse_label TEXT,
  home_blog_post_1_category TEXT,
  home_blog_post_1_title TEXT,
  home_blog_post_1_excerpt TEXT,
  home_blog_post_1_image_alt TEXT,
  home_blog_post_2_category TEXT,
  home_blog_post_2_title TEXT,
  home_blog_post_2_excerpt TEXT,
  home_blog_post_2_image_alt TEXT,
  home_blog_post_3_category TEXT,
  home_blog_post_3_title TEXT,
  home_blog_post_3_excerpt TEXT,
  home_blog_post_3_image_alt TEXT,
  UNIQUE(slug, locale)
);
