CREATE TABLE IF NOT EXISTS ec_site_daily_horoscope (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  picker_eyebrow TEXT,
  picker_title_accent TEXT,
  picker_title_rest TEXT,
  picker_description TEXT,
  picker_helper_prefix TEXT,
  picker_helper_cta TEXT,
  picker_sign_1_name TEXT,
  picker_sign_1_dates TEXT,
  picker_sign_1_element TEXT,
  picker_sign_2_name TEXT,
  picker_sign_2_dates TEXT,
  picker_sign_2_element TEXT,
  picker_sign_3_name TEXT,
  picker_sign_3_dates TEXT,
  picker_sign_3_element TEXT,
  picker_sign_4_name TEXT,
  picker_sign_4_dates TEXT,
  picker_sign_4_element TEXT,
  picker_sign_5_name TEXT,
  picker_sign_5_dates TEXT,
  picker_sign_5_element TEXT,
  picker_sign_6_name TEXT,
  picker_sign_6_dates TEXT,
  picker_sign_6_element TEXT,
  picker_sign_7_name TEXT,
  picker_sign_7_dates TEXT,
  picker_sign_7_element TEXT,
  picker_sign_8_name TEXT,
  picker_sign_8_dates TEXT,
  picker_sign_8_element TEXT,
  picker_sign_9_name TEXT,
  picker_sign_9_dates TEXT,
  picker_sign_9_element TEXT,
  picker_sign_10_name TEXT,
  picker_sign_10_dates TEXT,
  picker_sign_10_element TEXT,
  picker_sign_11_name TEXT,
  picker_sign_11_dates TEXT,
  picker_sign_11_element TEXT,
  picker_sign_12_name TEXT,
  picker_sign_12_dates TEXT,
  picker_sign_12_element TEXT,
  seo_title TEXT,
  seo_description TEXT,
  seo_canonical_path TEXT,
  seo_robots TEXT,
  og_title TEXT,
  og_description TEXT,
  og_image TEXT,
  og_image_alt TEXT,
  twitter_card TEXT,
  twitter_title TEXT,
  twitter_description TEXT,
  twitter_image TEXT,
  UNIQUE(slug, locale)
);
