CREATE TABLE IF NOT EXISTS ec_site_astrologers (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  browse_eyebrow TEXT,
  browse_title_accent TEXT,
  browse_title_suffix TEXT,
  browse_description TEXT,
  search_aria TEXT,
  search_placeholder TEXT,
  search_submit TEXT,
  search_clear TEXT,
  filter_label TEXT,
  filter_all TEXT,
  filter_love TEXT,
  filter_career TEXT,
  filter_life_path TEXT,
  filter_timing TEXT,
  filter_spiritual TEXT,
  online_now TEXT,
  busy_label TEXT,
  offline_label TEXT,
  results_suffix TEXT,
  no_results_title TEXT,
  no_results_body TEXT,
  profile_action TEXT,
  talk_now TEXT,
  book_next_slot TEXT,
  schedule TEXT,
  rate_unit TEXT,
  reviews_suffix TEXT,
  seo_title TEXT,
  seo_description TEXT,
  seo_canonical_path TEXT,
  seo_robots TEXT,
  og_title TEXT,
  og_description TEXT,
  og_image TEXT,
  og_image_alt TEXT,
  twitter_card TEXT,
  twitter_title TEXT,
  twitter_description TEXT,
  twitter_image TEXT,
  UNIQUE(slug, locale)
);
