ALTER TABLE ec_site_reports ADD COLUMN detail_pdf_label TEXT;
ALTER TABLE ec_site_reports ADD COLUMN detail_delivery_label TEXT;
ALTER TABLE ec_site_reports ADD COLUMN detail_buy_label TEXT;
ALTER TABLE ec_site_reports ADD COLUMN detail_purchase_note TEXT;
ALTER TABLE ec_site_reports ADD COLUMN detail_inside_label TEXT;
ALTER TABLE ec_site_reports ADD COLUMN detail_sample_label TEXT;

CREATE TABLE IF NOT EXISTS ec_site_report_details (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  detail_report_1_long_description TEXT,
  detail_report_1_chapter_1_title TEXT,
  detail_report_1_chapter_1_description TEXT,
  detail_report_1_chapter_2_title TEXT,
  detail_report_1_chapter_2_description TEXT,
  detail_report_1_chapter_3_title TEXT,
  detail_report_1_chapter_3_description TEXT,
  detail_report_1_chapter_4_title TEXT,
  detail_report_1_chapter_4_description TEXT,
  detail_report_1_chapter_5_title TEXT,
  detail_report_1_chapter_5_description TEXT,
  detail_report_1_sample TEXT,
  detail_report_2_long_description TEXT,
  detail_report_2_chapter_1_title TEXT,
  detail_report_2_chapter_1_description TEXT,
  detail_report_2_chapter_2_title TEXT,
  detail_report_2_chapter_2_description TEXT,
  detail_report_2_chapter_3_title TEXT,
  detail_report_2_chapter_3_description TEXT,
  detail_report_2_chapter_4_title TEXT,
  detail_report_2_chapter_4_description TEXT,
  detail_report_2_chapter_5_title TEXT,
  detail_report_2_chapter_5_description TEXT,
  detail_report_2_sample TEXT,
  detail_report_3_long_description TEXT,
  detail_report_3_chapter_1_title TEXT,
  detail_report_3_chapter_1_description TEXT,
  detail_report_3_chapter_2_title TEXT,
  detail_report_3_chapter_2_description TEXT,
  detail_report_3_chapter_3_title TEXT,
  detail_report_3_chapter_3_description TEXT,
  detail_report_3_chapter_4_title TEXT,
  detail_report_3_chapter_4_description TEXT,
  detail_report_3_chapter_5_title TEXT,
  detail_report_3_chapter_5_description TEXT,
  detail_report_3_sample TEXT,
  detail_report_4_long_description TEXT,
  detail_report_4_chapter_1_title TEXT,
  detail_report_4_chapter_1_description TEXT,
  detail_report_4_chapter_2_title TEXT,
  detail_report_4_chapter_2_description TEXT,
  detail_report_4_chapter_3_title TEXT,
  detail_report_4_chapter_3_description TEXT,
  detail_report_4_chapter_4_title TEXT,
  detail_report_4_chapter_4_description TEXT,
  detail_report_4_chapter_5_title TEXT,
  detail_report_4_chapter_5_description TEXT,
  detail_report_4_sample TEXT,
  detail_report_5_long_description TEXT,
  detail_report_5_chapter_1_title TEXT,
  detail_report_5_chapter_1_description TEXT,
  detail_report_5_chapter_2_title TEXT,
  detail_report_5_chapter_2_description TEXT,
  detail_report_5_chapter_3_title TEXT,
  detail_report_5_chapter_3_description TEXT,
  detail_report_5_chapter_4_title TEXT,
  detail_report_5_chapter_4_description TEXT,
  detail_report_5_chapter_5_title TEXT,
  detail_report_5_chapter_5_description TEXT,
  detail_report_5_sample TEXT,
  detail_report_6_long_description TEXT,
  detail_report_6_chapter_1_title TEXT,
  detail_report_6_chapter_1_description TEXT,
  detail_report_6_chapter_2_title TEXT,
  detail_report_6_chapter_2_description TEXT,
  detail_report_6_chapter_3_title TEXT,
  detail_report_6_chapter_3_description TEXT,
  detail_report_6_chapter_4_title TEXT,
  detail_report_6_chapter_4_description TEXT,
  detail_report_6_chapter_5_title TEXT,
  detail_report_6_chapter_5_description TEXT,
  detail_report_6_sample TEXT,
  UNIQUE(slug, locale)
);
