CREATE TABLE IF NOT EXISTS ec_site_shop (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  catalog_eyebrow TEXT,
  catalog_title_lead TEXT,
  catalog_title_accent TEXT,
  catalog_title_rest TEXT,
  catalog_description TEXT,
  catalog_filter_label TEXT,
  catalog_category_all TEXT,
  catalog_category_prints TEXT,
  catalog_category_books TEXT,
  catalog_category_home TEXT,
  catalog_category_jewelry TEXT,
  catalog_pieces_suffix TEXT,
  catalog_nav_shop_label TEXT,
  catalog_cart_label TEXT,
  seo_title TEXT,
  seo_description TEXT,
  seo_canonical_path TEXT,
  seo_robots TEXT,
  og_title TEXT,
  og_description TEXT,
  og_image TEXT,
  og_image_alt TEXT,
  twitter_card TEXT,
  twitter_title TEXT,
  twitter_description TEXT,
  twitter_image TEXT,
  UNIQUE(slug, locale)
);
