CREATE TABLE IF NOT EXISTS ec_site_blog (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  title TEXT NOT NULL DEFAULT '',
  blog_intro_eyebrow TEXT,
  blog_intro_title_accent TEXT,
  blog_intro_title_rest TEXT,
  blog_featured_eyebrow TEXT,
  blog_featured_title TEXT,
  blog_featured_excerpt TEXT,
  blog_featured_author TEXT,
  blog_featured_read_time TEXT,
  seo_title TEXT,
  seo_description TEXT,
  seo_canonical_path TEXT,
  seo_robots TEXT,
  og_title TEXT,
  og_description TEXT,
  og_image TEXT,
  og_image_alt TEXT,
  twitter_card TEXT,
  twitter_title TEXT,
  twitter_description TEXT,
  twitter_image TEXT,
  UNIQUE(slug, locale)
);
