CREATE TABLE IF NOT EXISTS ec_site_shop_catalog (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  shop_catalog_aria_label TEXT,
  shop_personalized_label TEXT,
  shop_view_label TEXT,
  shop_add_label TEXT,
  shop_product_natal_print_title TEXT,
  shop_product_natal_print_unit TEXT,
  shop_product_natal_print_fallback_label TEXT,
  shop_product_tapestry_title TEXT,
  shop_product_tapestry_unit TEXT,
  shop_product_tapestry_fallback_label TEXT,
  shop_product_almanac_title TEXT,
  shop_product_almanac_unit TEXT,
  shop_product_almanac_fallback_label TEXT,
  shop_product_tarot_title TEXT,
  shop_product_tarot_unit TEXT,
  shop_product_tarot_fallback_label TEXT,
  shop_product_notebook_title TEXT,
  shop_product_notebook_unit TEXT,
  shop_product_notebook_fallback_label TEXT,
  shop_product_candle_title TEXT,
  shop_product_candle_unit TEXT,
  shop_product_candle_fallback_label TEXT,
  shop_product_scarf_title TEXT,
  shop_product_scarf_unit TEXT,
  shop_product_scarf_fallback_label TEXT,
  shop_product_pins_title TEXT,
  shop_product_pins_unit TEXT,
  shop_product_pins_fallback_label TEXT,
  shop_product_pendant_title TEXT,
  shop_product_pendant_unit TEXT,
  shop_product_pendant_fallback_label TEXT,
  shop_perk_1_title TEXT,
  shop_perk_1_description TEXT,
  shop_perk_2_title TEXT,
  shop_perk_2_description TEXT,
  shop_perk_3_title TEXT,
  shop_perk_3_description TEXT,
  UNIQUE(slug, locale)
);
