CREATE TABLE IF NOT EXISTS ec_site_daily_horoscope_cta (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  personalized_cta_eyebrow TEXT,
  personalized_cta_title_lead TEXT,
  personalized_cta_title_accent TEXT,
  personalized_cta_title_rest TEXT,
  personalized_cta_description TEXT,
  personalized_cta_primary_label TEXT,
  personalized_cta_secondary_label TEXT,
  UNIQUE(slug, locale)
);
