-- Move the existing profile field family out of the primary Astrologers table.
-- This keeps both collections below D1's bounded column limit while preserving
-- every locale row, publication state, and draft/live revision reference.
PRAGMA foreign_keys = OFF;
BEGIN IMMEDIATE;

CREATE TABLE IF NOT EXISTS ec_site_astrologer_profiles (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  profile_back_label TEXT,
  profile_years_reading TEXT,
  profile_sessions TEXT,
  profile_languages TEXT,
  profile_about TEXT,
  profile_specialties TEXT,
  profile_what_to_expect TEXT,
  profile_expectation_one TEXT,
  profile_expectation_two TEXT,
  profile_expectation_three TEXT,
  profile_expectation_four TEXT,
  profile_recent_reviews TEXT,
  profile_average TEXT,
  profile_reviews_suffix TEXT,
  profile_rate_unit TEXT,
  profile_talk_now TEXT,
  profile_book_next_slot TEXT,
  profile_schedule TEXT,
  profile_written_question TEXT,
  profile_free_minutes_note TEXT,
  profile_chart_ready TEXT,
  profile_chart_owner TEXT,
  profile_chart_label TEXT,
  profile_review_one_date TEXT,
  profile_review_one_text TEXT,
  profile_review_two_date TEXT,
  profile_review_two_text TEXT,
  profile_review_three_date TEXT,
  profile_review_three_text TEXT,
  UNIQUE(slug, locale)
);

INSERT OR REPLACE INTO ec_site_astrologer_profiles (
  id,
  slug,
  status,
  author_id,
  primary_byline_id,
  created_at,
  updated_at,
  published_at,
  scheduled_at,
  deleted_at,
  version,
  live_revision_id,
  draft_revision_id,
  locale,
  translation_group,
  profile_back_label,
  profile_years_reading,
  profile_sessions,
  profile_languages,
  profile_about,
  profile_specialties,
  profile_what_to_expect,
  profile_expectation_one,
  profile_expectation_two,
  profile_expectation_three,
  profile_expectation_four,
  profile_recent_reviews,
  profile_average,
  profile_reviews_suffix,
  profile_rate_unit,
  profile_talk_now,
  profile_book_next_slot,
  profile_schedule,
  profile_written_question,
  profile_free_minutes_note,
  profile_chart_ready,
  profile_chart_owner,
  profile_chart_label,
  profile_review_one_date,
  profile_review_one_text,
  profile_review_two_date,
  profile_review_two_text,
  profile_review_three_date,
  profile_review_three_text
)
SELECT
  id,
  'profiles',
  status,
  author_id,
  primary_byline_id,
  created_at,
  updated_at,
  published_at,
  scheduled_at,
  deleted_at,
  version,
  live_revision_id,
  draft_revision_id,
  locale,
  translation_group,
  profile_back_label,
  profile_years_reading,
  profile_sessions,
  profile_languages,
  profile_about,
  profile_specialties,
  profile_what_to_expect,
  profile_expectation_one,
  profile_expectation_two,
  profile_expectation_three,
  profile_expectation_four,
  profile_recent_reviews,
  profile_average,
  profile_reviews_suffix,
  profile_rate_unit,
  profile_talk_now,
  profile_book_next_slot,
  profile_schedule,
  profile_written_question,
  profile_free_minutes_note,
  profile_chart_ready,
  profile_chart_owner,
  profile_chart_label,
  profile_review_one_date,
  profile_review_one_text,
  profile_review_two_date,
  profile_review_two_text,
  profile_review_three_date,
  profile_review_three_text
FROM ec_site_astrologers;

DROP TABLE IF EXISTS ec_site_astrologers_compact;

CREATE TABLE ec_site_astrologers_compact (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  browse_eyebrow TEXT,
  browse_title_accent TEXT,
  browse_title_suffix TEXT,
  browse_description TEXT,
  search_aria TEXT,
  search_placeholder TEXT,
  search_submit TEXT,
  search_clear TEXT,
  filter_label TEXT,
  filter_all TEXT,
  filter_love TEXT,
  filter_career TEXT,
  filter_life_path TEXT,
  filter_timing TEXT,
  filter_spiritual TEXT,
  online_now TEXT,
  busy_label TEXT,
  offline_label TEXT,
  results_suffix TEXT,
  no_results_title TEXT,
  no_results_body TEXT,
  profile_action TEXT,
  talk_now TEXT,
  book_next_slot TEXT,
  schedule TEXT,
  rate_unit TEXT,
  reviews_suffix TEXT,
  seo_title TEXT,
  seo_description TEXT,
  seo_canonical_path TEXT,
  seo_robots TEXT,
  og_title TEXT,
  og_description TEXT,
  og_image TEXT,
  og_image_alt TEXT,
  twitter_card TEXT,
  twitter_title TEXT,
  twitter_description TEXT,
  twitter_image TEXT,
  UNIQUE(slug, locale)
);

INSERT INTO ec_site_astrologers_compact
SELECT
  id,
  slug,
  status,
  author_id,
  primary_byline_id,
  created_at,
  updated_at,
  published_at,
  scheduled_at,
  deleted_at,
  version,
  live_revision_id,
  draft_revision_id,
  locale,
  translation_group,
  browse_eyebrow,
  browse_title_accent,
  browse_title_suffix,
  browse_description,
  search_aria,
  search_placeholder,
  search_submit,
  search_clear,
  filter_label,
  filter_all,
  filter_love,
  filter_career,
  filter_life_path,
  filter_timing,
  filter_spiritual,
  online_now,
  busy_label,
  offline_label,
  results_suffix,
  no_results_title,
  no_results_body,
  profile_action,
  talk_now,
  book_next_slot,
  schedule,
  rate_unit,
  reviews_suffix,
  seo_title,
  seo_description,
  seo_canonical_path,
  seo_robots,
  og_title,
  og_description,
  og_image,
  og_image_alt,
  twitter_card,
  twitter_title,
  twitter_description,
  twitter_image
FROM ec_site_astrologers;

DROP TABLE ec_site_astrologers;
ALTER TABLE ec_site_astrologers_compact RENAME TO ec_site_astrologers;

COMMIT;
PRAGMA foreign_keys = ON;
