CREATE TABLE IF NOT EXISTS ec_site_blog_articles (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  title TEXT NOT NULL DEFAULT '',
  blog_article_back_label TEXT,
  blog_article_lot_fortune_category TEXT,
  blog_article_lot_fortune_date TEXT,
  blog_article_aries_rising_author TEXT,
  blog_article_aries_rising_date TEXT,
  blog_article_morning_star_author TEXT,
  blog_article_morning_star_date TEXT,
  blog_article_saturn_return_author TEXT,
  blog_article_saturn_return_date TEXT,
  blog_article_twelve_houses_author TEXT,
  blog_article_twelve_houses_date TEXT,
  blog_article_mercury_retrograde_author TEXT,
  blog_article_mercury_retrograde_date TEXT,
  UNIQUE(slug, locale)
);
