CREATE TABLE IF NOT EXISTS ec_site_shop_product_detail (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  shop_detail_breadcrumb_label TEXT,
  shop_detail_reviews_label TEXT,
  shop_detail_personalized_eyebrow TEXT,
  shop_detail_personalized_chart_label TEXT,
  shop_detail_add_label TEXT,
  shop_detail_shipping_status_label TEXT,
  shop_detail_in_box_label TEXT,
  shop_detail_related_label TEXT,
  shop_detail_quantity_label TEXT,
  shop_detail_quantity_value_label TEXT,
  shop_detail_decrement_label TEXT,
  shop_detail_increment_label TEXT,
  shop_detail_natal_print_variant_label TEXT,
  shop_detail_natal_print_variant_option_1 TEXT,
  shop_detail_natal_print_variant_option_2 TEXT,
  shop_detail_natal_print_variant_option_3 TEXT,
  shop_detail_tapestry_variant_label TEXT,
  shop_detail_tapestry_variant_option_1 TEXT,
  shop_detail_tapestry_variant_option_2 TEXT,
  shop_detail_notebook_variant_label TEXT,
  shop_detail_notebook_variant_option_1 TEXT,
  shop_detail_notebook_variant_option_2 TEXT,
  shop_detail_candle_variant_label TEXT,
  shop_detail_candle_variant_option_1 TEXT,
  shop_detail_candle_variant_option_2 TEXT,
  shop_detail_candle_variant_option_3 TEXT,
  shop_detail_pins_variant_label TEXT,
  shop_detail_pins_variant_option_1 TEXT,
  shop_detail_pins_variant_option_2 TEXT,
  shop_detail_pins_variant_option_3 TEXT,
  shop_detail_pins_variant_option_4 TEXT,
  shop_detail_pendant_variant_label TEXT,
  shop_detail_pendant_variant_option_1 TEXT,
  shop_detail_pendant_variant_option_2 TEXT,
  UNIQUE(slug, locale)
);

CREATE TABLE IF NOT EXISTS ec_site_shop_product_descriptions (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  shop_detail_natal_print_description TEXT,
  shop_detail_natal_print_ship_note TEXT,
  shop_detail_natal_print_include_1 TEXT,
  shop_detail_natal_print_include_2 TEXT,
  shop_detail_natal_print_include_3 TEXT,
  shop_detail_natal_print_include_4 TEXT,
  shop_detail_tapestry_description TEXT,
  shop_detail_tapestry_ship_note TEXT,
  shop_detail_tapestry_include_1 TEXT,
  shop_detail_tapestry_include_2 TEXT,
  shop_detail_tapestry_include_3 TEXT,
  shop_detail_tapestry_include_4 TEXT,
  shop_detail_almanac_description TEXT,
  shop_detail_almanac_ship_note TEXT,
  shop_detail_almanac_include_1 TEXT,
  shop_detail_almanac_include_2 TEXT,
  shop_detail_almanac_include_3 TEXT,
  shop_detail_almanac_include_4 TEXT,
  shop_detail_tarot_description TEXT,
  shop_detail_tarot_ship_note TEXT,
  shop_detail_tarot_include_1 TEXT,
  shop_detail_tarot_include_2 TEXT,
  shop_detail_tarot_include_3 TEXT,
  shop_detail_tarot_include_4 TEXT,
  shop_detail_notebook_description TEXT,
  shop_detail_notebook_ship_note TEXT,
  shop_detail_notebook_include_1 TEXT,
  shop_detail_notebook_include_2 TEXT,
  shop_detail_notebook_include_3 TEXT,
  shop_detail_notebook_include_4 TEXT,
  shop_detail_candle_description TEXT,
  shop_detail_candle_ship_note TEXT,
  shop_detail_candle_include_1 TEXT,
  shop_detail_candle_include_2 TEXT,
  shop_detail_candle_include_3 TEXT,
  shop_detail_candle_include_4 TEXT,
  shop_detail_scarf_description TEXT,
  shop_detail_scarf_ship_note TEXT,
  shop_detail_scarf_include_1 TEXT,
  shop_detail_scarf_include_2 TEXT,
  shop_detail_scarf_include_3 TEXT,
  shop_detail_scarf_include_4 TEXT,
  shop_detail_pins_description TEXT,
  shop_detail_pins_ship_note TEXT,
  shop_detail_pins_include_1 TEXT,
  shop_detail_pins_include_2 TEXT,
  shop_detail_pins_include_3 TEXT,
  shop_detail_pins_include_4 TEXT,
  shop_detail_pendant_description TEXT,
  shop_detail_pendant_ship_note TEXT,
  shop_detail_pendant_include_1 TEXT,
  shop_detail_pendant_include_2 TEXT,
  shop_detail_pendant_include_3 TEXT,
  shop_detail_pendant_include_4 TEXT,
  UNIQUE(slug, locale)
);
