CREATE TABLE IF NOT EXISTS ec_site_blog_article_bodies (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  title TEXT NOT NULL DEFAULT '',
  blog_article_author_bio TEXT,
  blog_article_lot_fortune_body_1 TEXT,
  blog_article_lot_fortune_body_2 TEXT,
  blog_article_lot_fortune_body_3 TEXT,
  blog_article_lot_fortune_body_4 TEXT,
  blog_article_lot_fortune_body_5 TEXT,
  blog_article_lot_fortune_body_6 TEXT,
  blog_article_lot_fortune_body_7 TEXT,
  blog_article_lot_fortune_body_8 TEXT,
  blog_article_aries_rising_body_1 TEXT,
  blog_article_aries_rising_body_2 TEXT,
  blog_article_aries_rising_body_3 TEXT,
  blog_article_aries_rising_body_4 TEXT,
  blog_article_aries_rising_body_5 TEXT,
  blog_article_aries_rising_body_6 TEXT,
  blog_article_aries_rising_body_7 TEXT,
  blog_article_morning_star_body_1 TEXT,
  blog_article_morning_star_body_2 TEXT,
  blog_article_morning_star_body_3 TEXT,
  blog_article_morning_star_body_4 TEXT,
  blog_article_morning_star_body_5 TEXT,
  blog_article_morning_star_body_6 TEXT,
  blog_article_morning_star_body_7 TEXT,
  blog_article_saturn_return_body_1 TEXT,
  blog_article_saturn_return_body_2 TEXT,
  blog_article_saturn_return_body_3 TEXT,
  blog_article_saturn_return_body_4 TEXT,
  blog_article_saturn_return_body_5 TEXT,
  blog_article_saturn_return_body_6 TEXT,
  blog_article_saturn_return_body_7 TEXT,
  blog_article_twelve_houses_body_1 TEXT,
  blog_article_twelve_houses_body_2 TEXT,
  blog_article_twelve_houses_body_3 TEXT,
  blog_article_twelve_houses_body_4 TEXT,
  blog_article_twelve_houses_body_5 TEXT,
  blog_article_twelve_houses_body_6 TEXT,
  blog_article_twelve_houses_body_7 TEXT,
  blog_article_mercury_retrograde_body_1 TEXT,
  blog_article_mercury_retrograde_body_2 TEXT,
  blog_article_mercury_retrograde_body_3 TEXT,
  blog_article_mercury_retrograde_body_4 TEXT,
  blog_article_mercury_retrograde_body_5 TEXT,
  blog_article_mercury_retrograde_body_6 TEXT,
  blog_article_mercury_retrograde_body_7 TEXT,
  UNIQUE(slug, locale)
);
