CREATE TABLE IF NOT EXISTS ec_site_signup (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  title TEXT NOT NULL DEFAULT '',
  signup_brand_label TEXT,
  signup_brand_aria_label TEXT,
  signup_back_label TEXT,
  signup_panel_kicker TEXT,
  signup_panel_title TEXT,
  signup_panel_description TEXT,
  signup_proof_1_label TEXT,
  signup_proof_2_label TEXT,
  seo_title TEXT,
  seo_description TEXT,
  seo_canonical_path TEXT,
  seo_robots TEXT,
  og_title TEXT,
  og_description TEXT,
  og_image TEXT,
  og_image_alt TEXT,
  twitter_card TEXT,
  twitter_title TEXT,
  twitter_description TEXT,
  twitter_image TEXT,
  UNIQUE(slug, locale)
);
