-- Keep the final Astrologer flow state in its own bounded Content Studio
-- collection instead of pushing the Session setup table over D1's column cap.
CREATE TABLE IF NOT EXISTS ec_site_astrologers_session_summary (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  summary_live_overline TEXT,
  summary_live_title TEXT,
  summary_live_body TEXT,
  summary_booked_overline TEXT,
  summary_booked_title TEXT,
  summary_booked_body TEXT,
  summary_sent_overline TEXT,
  summary_sent_title TEXT,
  summary_sent_body TEXT,
  summary_session_type_label TEXT,
  summary_duration_label TEXT,
  summary_free_intro_label TEXT,
  summary_free_intro_value TEXT,
  summary_billed_at_label TEXT,
  summary_when_label TEXT,
  summary_length_label TEXT,
  summary_type_label TEXT,
  summary_reply_by_label TEXT,
  summary_chart_label TEXT,
  summary_shared_value TEXT,
  summary_total_charged_label TEXT,
  summary_estimated_total_label TEXT,
  summary_rating_title TEXT,
  summary_rating_aria_label TEXT,
  summary_note_placeholder TEXT,
  summary_live_primary_action TEXT,
  summary_booked_primary_action TEXT,
  summary_sent_primary_action TEXT,
  summary_back_action TEXT,
  summary_return_home TEXT,
  UNIQUE(slug, locale)
);
