CREATE TABLE IF NOT EXISTS ec_site_shop_checkout_flow (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  title TEXT NOT NULL DEFAULT '',
  shop_cart_continue_label TEXT,
  shop_cart_title TEXT,
  shop_cart_empty_title TEXT,
  shop_cart_empty_description TEXT,
  shop_cart_browse_label TEXT,
  shop_order_summary_title TEXT,
  shop_order_subtotal_label TEXT,
  shop_order_shipping_label TEXT,
  shop_order_shipping_free_label TEXT,
  shop_order_free_shipping_prefix TEXT,
  shop_order_free_shipping_suffix TEXT,
  shop_order_total_label TEXT,
  shop_cart_checkout_label TEXT,
  shop_cart_secure_note TEXT,
  shop_cart_quantity_label TEXT,
  shop_cart_remove_label TEXT,
  shop_cart_decrement_label TEXT,
  shop_cart_increment_label TEXT,
  shop_checkout_back_label TEXT,
  shop_checkout_title TEXT,
  shop_checkout_contact_title TEXT,
  shop_checkout_email_placeholder TEXT,
  shop_checkout_shipping_title TEXT,
  shop_checkout_first_name_placeholder TEXT,
  shop_checkout_last_name_placeholder TEXT,
  shop_checkout_street_placeholder TEXT,
  shop_checkout_city_placeholder TEXT,
  shop_checkout_state_placeholder TEXT,
  shop_checkout_postal_placeholder TEXT,
  shop_checkout_country_placeholder TEXT,
  shop_checkout_payment_title TEXT,
  shop_checkout_encrypted_label TEXT,
  shop_checkout_card_number_placeholder TEXT,
  shop_checkout_card_name_placeholder TEXT,
  shop_checkout_expiry_placeholder TEXT,
  shop_checkout_cvc_placeholder TEXT,
  shop_checkout_order_title TEXT,
  shop_checkout_tax_label TEXT,
  shop_checkout_place_order_label TEXT,
  shop_checkout_place_order_note TEXT,
  shop_confirmation_eyebrow TEXT,
  shop_confirmation_title TEXT,
  shop_confirmation_thanks_prefix TEXT,
  shop_confirmation_thanks_suffix TEXT,
  shop_confirmation_order_number_label TEXT,
  shop_confirmation_arrives_label TEXT,
  shop_confirmation_total_paid_label TEXT,
  shop_confirmation_continue_label TEXT,
  shop_confirmation_home_label TEXT,
  shop_confirmation_default_first_name TEXT,
  shop_confirmation_arrival_label TEXT,
  UNIQUE(slug, locale)
);
