CREATE TABLE IF NOT EXISTS ec_site_wallet (
  id TEXT PRIMARY KEY,
  locale TEXT NOT NULL UNIQUE,
  seo_title TEXT NOT NULL,
  seo_description TEXT NOT NULL,
  eyebrow TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  available TEXT NOT NULL,
  add_funds TEXT NOT NULL,
  choose_amount TEXT NOT NULL,
  custom_amount TEXT NOT NULL,
  minimum TEXT NOT NULL,
  pay TEXT NOT NULL,
  preparing TEXT NOT NULL,
  activity TEXT NOT NULL,
  empty TEXT NOT NULL,
  balance_after TEXT NOT NULL,
  success_title TEXT NOT NULL,
  success_body TEXT NOT NULL,
  verifying TEXT NOT NULL,
  cancelled_title TEXT NOT NULL,
  cancelled_body TEXT NOT NULL,
  failed_title TEXT NOT NULL,
  failed_body TEXT NOT NULL,
  retry TEXT NOT NULL,
  browse TEXT NOT NULL,
  bonus TEXT NOT NULL,
  secure TEXT NOT NULL,
  seo_canonical_path TEXT NOT NULL,
  seo_robots TEXT NOT NULL,
  og_title TEXT NOT NULL,
  og_description TEXT NOT NULL,
  og_image TEXT NOT NULL,
  og_image_alt TEXT NOT NULL,
  twitter_card TEXT NOT NULL,
  twitter_title TEXT NOT NULL,
  twitter_description TEXT NOT NULL,
  twitter_image TEXT NOT NULL,
  created_at TEXT,
  updated_at TEXT
);
