-- Account's primary content table is at D1's safe column boundary. Keep the
-- Wallet section in a bounded supplemental collection.
CREATE TABLE IF NOT EXISTS ec_site_account_wallet (
  id TEXT PRIMARY KEY,
  slug TEXT,
  status TEXT DEFAULT 'draft',
  author_id TEXT,
  primary_byline_id TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  published_at TEXT,
  scheduled_at TEXT,
  deleted_at TEXT,
  version INTEGER DEFAULT 1,
  live_revision_id TEXT,
  draft_revision_id TEXT,
  locale TEXT DEFAULT 'en' NOT NULL,
  translation_group TEXT,
  account_nav_wallet_label TEXT,
  account_wallet_eyebrow TEXT,
  account_wallet_title TEXT,
  account_wallet_description TEXT,
  account_wallet_entries_label TEXT,
  account_wallet_available_label TEXT,
  account_wallet_usage TEXT,
  account_wallet_add_label TEXT,
  account_wallet_browse_label TEXT,
  account_wallet_history_label TEXT,
  account_wallet_balance_after_label TEXT,
  account_wallet_credit_fallback TEXT,
  account_wallet_debit_fallback TEXT,
  account_wallet_empty_title TEXT,
  account_wallet_empty_description TEXT,
  UNIQUE(slug, locale)
);
